"""V2 protocol constants for the AG99live desktop adapter."""

from __future__ import annotations

PROTOCOL_VERSION = "v2"

SOURCE_FRONTEND = "frontend"
SOURCE_ADAPTER = "adapter"
SOURCE_ASTRBOT = "astrbot"
SOURCE_ENGINE = "engine"

TYPE_INPUT_TEXT = "input.text"
TYPE_INPUT_AUDIO_STREAM_START = "input.audio_stream_start"
TYPE_INPUT_AUDIO_STREAM_CHUNK = "input.audio_stream_chunk"
TYPE_INPUT_AUDIO_STREAM_END = "input.audio_stream_end"
TYPE_INPUT_MIC_AUDIO_DATA = "input.mic_audio_data"
TYPE_INPUT_RAW_AUDIO_DATA = "input.raw_audio_data"
TYPE_INPUT_MIC_AUDIO_END = "input.mic_audio_end"

TYPE_OUTPUT_TEXT = "output.text"
TYPE_OUTPUT_AUDIO = "output.audio"
TYPE_OUTPUT_IMAGE = "output.image"
TYPE_OUTPUT_TRANSCRIPTION = "output.transcription"

TYPE_CONTROL_TURN_STARTED = "control.turn_started"
TYPE_CONTROL_TURN_FINISHED = "control.turn_finished"
TYPE_CONTROL_INTERRUPT = "control.interrupt"
TYPE_CONTROL_PLAYBACK_FINISHED = "control.playback_finished"
TYPE_CONTROL_START_MIC = "control.start_mic"
TYPE_CONTROL_SYNTH_FINISHED = "control.synth_finished"
TYPE_CONTROL_ERROR = "control.error"

TYPE_SYSTEM_SERVER_INFO = "system.server_info"
TYPE_SYSTEM_MODEL_SYNC = "system.model_sync"
TYPE_SYSTEM_GROUP_UPDATE = "system.group_update"
TYPE_SYSTEM_BACKGROUND_LIST_REQUEST = "system.background_list_request"
TYPE_SYSTEM_BACKGROUND_LIST = "system.background_list"
TYPE_SYSTEM_HISTORY_LIST_REQUEST = "system.history_list_request"
TYPE_SYSTEM_HISTORY_LIST = "system.history_list"
TYPE_SYSTEM_HISTORY_CREATE = "system.history_create"
TYPE_SYSTEM_HISTORY_CREATED = "system.history_created"
TYPE_SYSTEM_HISTORY_LOAD = "system.history_load"
TYPE_SYSTEM_HISTORY_DATA = "system.history_data"
TYPE_SYSTEM_HISTORY_DELETE = "system.history_delete"
TYPE_SYSTEM_HISTORY_DELETED = "system.history_deleted"
TYPE_SYSTEM_HEARTBEAT = "system.heartbeat"
TYPE_SYSTEM_HEARTBEAT_ACK = "system.heartbeat_ack"

TYPE_ENGINE_MOTION_PLAN = "engine.motion_plan"
TYPE_ENGINE_MOTION_INTENT = "engine.motion_intent"
TYPE_ENGINE_EXPRESSION_PLAN = "engine.expression_plan"
TYPE_ENGINE_IDLE_STATE = "engine.idle_state"
TYPE_ENGINE_LOOK_TARGET = "engine.look_target"

INPUT_TYPES = {
    TYPE_INPUT_TEXT,
    TYPE_INPUT_AUDIO_STREAM_START,
    TYPE_INPUT_AUDIO_STREAM_CHUNK,
    TYPE_INPUT_AUDIO_STREAM_END,
    TYPE_INPUT_MIC_AUDIO_DATA,
    TYPE_INPUT_RAW_AUDIO_DATA,
    TYPE_INPUT_MIC_AUDIO_END,
}

OUTPUT_TYPES = {
    TYPE_OUTPUT_TEXT,
    TYPE_OUTPUT_AUDIO,
    TYPE_OUTPUT_IMAGE,
    TYPE_OUTPUT_TRANSCRIPTION,
}

CONTROL_TYPES = {
    TYPE_CONTROL_TURN_STARTED,
    TYPE_CONTROL_TURN_FINISHED,
    TYPE_CONTROL_INTERRUPT,
    TYPE_CONTROL_PLAYBACK_FINISHED,
    TYPE_CONTROL_START_MIC,
    TYPE_CONTROL_SYNTH_FINISHED,
    TYPE_CONTROL_ERROR,
}

SYSTEM_TYPES = {
    TYPE_SYSTEM_SERVER_INFO,
    TYPE_SYSTEM_MODEL_SYNC,
    TYPE_SYSTEM_GROUP_UPDATE,
    TYPE_SYSTEM_BACKGROUND_LIST_REQUEST,
    TYPE_SYSTEM_BACKGROUND_LIST,
    TYPE_SYSTEM_HISTORY_LIST_REQUEST,
    TYPE_SYSTEM_HISTORY_LIST,
    TYPE_SYSTEM_HISTORY_CREATE,
    TYPE_SYSTEM_HISTORY_CREATED,
    TYPE_SYSTEM_HISTORY_LOAD,
    TYPE_SYSTEM_HISTORY_DATA,
    TYPE_SYSTEM_HISTORY_DELETE,
    TYPE_SYSTEM_HISTORY_DELETED,
    TYPE_SYSTEM_HEARTBEAT,
    TYPE_SYSTEM_HEARTBEAT_ACK,
}

ENGINE_TYPES = {
    TYPE_ENGINE_MOTION_PLAN,
    TYPE_ENGINE_MOTION_INTENT,
    TYPE_ENGINE_EXPRESSION_PLAN,
    TYPE_ENGINE_IDLE_STATE,
    TYPE_ENGINE_LOOK_TARGET,
}

KNOWN_MESSAGE_TYPES = INPUT_TYPES | OUTPUT_TYPES | CONTROL_TYPES | SYSTEM_TYPES | ENGINE_TYPES

INBOUND_ALLOWED_TYPES = {
    *INPUT_TYPES,
    TYPE_CONTROL_PLAYBACK_FINISHED,
    TYPE_CONTROL_INTERRUPT,
    TYPE_ENGINE_MOTION_PLAN,
    TYPE_ENGINE_MOTION_INTENT,
    TYPE_SYSTEM_BACKGROUND_LIST_REQUEST,
    TYPE_SYSTEM_HISTORY_LIST_REQUEST,
    TYPE_SYSTEM_HISTORY_CREATE,
    TYPE_SYSTEM_HISTORY_LOAD,
    TYPE_SYSTEM_HISTORY_DELETE,
    TYPE_SYSTEM_HEARTBEAT,
}
